### ISSUE TITLE
Question: SSH login

### ISSUE THREAD

**Issue by michaelcyyuen** [dev-sec/hardening#11]
Hi Experts,

I've ran the knife solo bootstrap command to a DigitalOcean server, using the Chef all in one example.
Then I've got  "Too many authentication failures" when trying to ssh it.
Anything special I should config before or afterwards to fix this?

Cheers,
Michael

**Comment by atomic111** [comment]
@michaelcyyuen sorry for the late response. do you need any help?

**Comment by michaelcyyuen** [comment]
I've managed to follow the other readme in other related projects to run the script.

So far ok! Thx!
