### ISSUE TITLE
Keep repo up to date

### ISSUE THREAD

**Issue by zamber** [dev-sec/hardening#12]
Hi,

It's kinda pointless to have an example repo that's 2 years behind all across the line.

**Comment by chris-rock** [comment]
@zamber Thank you for your feedback. As you may have seen the devsec project is very active. Nevertheless, I agree that the examples have not fully kept up with our expectations. We are always looking for contributors to improve the situation.

I'd like to understand your what you were looking for, what your expectations have been and how you would like to see this work? This would help us to make it most useful for our users. And maybe you can help us as well?

**Comment by zamber** [comment]
1. initial entry organic to http://dev-sec.io
2. scrolled down and wanted to see an all-in-one example for Ansible
3. noticed that it was last updated 2y ago and that it only has SSH hardening (where the website additionally states nginx and mysql)
4. backed up to the website to navigate to one module
5. saw that it's nicely maintained and active
6. reported this issue

I would expect that the all-in-one repo would be at least up to date with modules that were subsequently added (nginx, mysql).

Ideally the demo repo would be updated each time there are changes in the submodules (preferably automagically as part of integration testing but that can be overkill).

My concern here is that this is an entry point for newcomers that's lined on the main project page. The health of the demo should reflect the health of the project, otherwise less curious people will just close it instantly and mark it as a dead project.

**Comment by chris-rock** [comment]
@zamber Thank you for your honest feedback. I fully agree with you. Maybe you can help us and help us to update the ansible demo?

**Comment by chris-rock** [comment]
@zamber Please let us know if you see anything missing
